version: "3.8"

services:
  db:
    image: postgres:13.5-alpine
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=C'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: /bin/sh
    volumes:
      - ./backend:/go/src/app
    ports:
      - 8080:8080
    depends_on:
      - db
    tty: true
    stdin_open: true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: /bin/sh -c 'yarn && yarn dev'
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    environment: 
      - NODE_ENV=development
    tty: true
